version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "db-name"
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  web:
    build: 
      context: .
    container_name: application
    restart: always
    volumes:
      - ./budgetproject:/app
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  # client:
  #   image: mysql:8.0.2
  #   depends_on:
  #     - mysql-dev
  #   command: mysql -uroot -ppassword -hmysql-dev my-app-db

